## STATIC CONFIGURATION
log:
  level: INFO

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "npipe:////.//pipe//docker_engine"
    #endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true