http:
 #region routers
  routers:
# vcenter http
    vcenter:
      entryPoints:
        - "http"
      rule: "Host(`vcenter.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: vcenter
# vcenter https
    vcenter-secure:
      entryPoints:
        - "https"
      rule: "Host(`vcenter.cinderblock.tech`)"
      middlewares:
        - default-headers
      tls: {}
      service: vcenter
# Esxi http
    esxi:
      entryPoints:
        - "http"
      rule: "Host(`esxi.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: esxi
# esxi https
    esxi-secure:
      entryPoints:
        - "https"
      rule: "Host(`esxi.cinderblock.tech`)"
      middlewares:
        - default-headers
      tls: {}
      service: esxi
# Truenas http
    truenas:
      entryPoints:
        - "http"
      rule: "Host(`truenas.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: truenas
# treunas https
    truenas-secure:
      entryPoints:
        - "https"
      rule: "Host(`truenas.cinderblock.tech`)"
      middlewares:
        - default-headers
      tls: {}
      service: truenas      
# Pihole http
    pihole:
      entryPoints:
        - "http"
      rule: "Host(`pihole.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: pihole
# Pihole https
    pihole-secure:
      entryPoints:
        - "https"
      rule: "Host(`pihole.cinderblock.tech`)"
      middlewares:
        - default-headers
        - addprefix-admin
      tls: {}
      service: pihole
# Dreamrouter http
    dreamrouter:
      entryPoints:
        - "http"
      rule: "Host(`dreamrouter.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: dreamrouter
# Dreamrouter https
    dreamrouter-secure:
      entryPoints:
        - "https"
      rule: "Host(`dreamrouter.cinderblock.tech`)"
      middlewares:
        - default-headers
      tls: {}
      service: dreamrouter
# Pterodactyl http
    pterodactyl:
      entryPoints:
        - "http"
      rule: "Host(`pterodactyl.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: pterodactyl
# Pterodactyl https
    pterodactyl-secure:
      entryPoints:
        - "https"
      rule: "Host(`pterodactyl.cinderblock.tech`)"
      middlewares:
        - default-headers
        - crowdsec-bouncer
      tls: {}
      service: pterodactyl
# Pterodactyl_wings http
    pterodactyl_wings-node01:
      entryPoints:
        - "http"
      rule: "Host(`gamenode-01.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: pterodactyl_wings-node01
# Pterodactyl_wings https
    pterodactyl_wings-node01-secure:
      entryPoints:
        - "https"
      rule: "Host(`gamenode-01.cinderblock.tech`)"
      middlewares:
        - default-headers
      tls: {}
      service: pterodactyl_wings-node01
# rancher http
#    rancher:
#      entryPoints:
#        - "http"
#      rule: "Host(`rancher.cinderblock.tech`)"
#      middlewares:
#        - https-redirectscheme
#      service: rancher
# rancher https
#    rancher-secure:
#      entryPoints:
#        - "https"
#      rule: "Host(`rancher.cinderblock.tech`)"
#      middlewares:
#        - default-headers
#      tls: {}
#      service: rancher
# openvpn http
    openvpn:
      entryPoints:
        - "http"
      rule: "Host(`vpn.cinderblock.tech`)"
      middlewares:
        - https-redirectscheme
      service: openvpn
# openvpn https
    openvpn-secure:
      entryPoints:
        - "https"
      rule: "Host(`vpn.cinderblock.tech`)"
      middlewares:
        - default-headers
      tls: {}
      service: openvpn
#region services
  services:
# truenas Loadbalancer
    truenas:
      loadBalancer:
        servers:
          - url: "https://192.168.1.85:443"
        passHostHeader: true
# vcenter Loadbalancer
    vcenter:
      loadBalancer:
        servers:
          - url: "https://192.168.1.95:443"
        passHostHeader: true
# esxi Loadbalancer
    esxi:
      loadBalancer:
        servers:
          - url: "https://192.168.1.90:443"
          - url: "https://192.168.1.90:443"
          - url: "https://192.168.1.90:443"
        passHostHeader: true
# Pihole Loadbalancer
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.1.253:80"
        passHostHeader: true
# Dreamrouter Loadbalancer
    dreamrouter:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1:443"
        passHostHeader: true
# Pterodactyl Loadbalancer
    pterodactyl:
      loadBalancer:
        servers:
          - url: "http://192.168.1.242:80"
        passHostHeader: true
# Pterodactyl_wings Loadbalancer
    pterodactyl_wings-node01:
      loadBalancer:
        servers:
          - url: "http://192.168.1.240:443"
        passHostHeader: true
# Rancher Loadbalancer
#    rancher:
#      loadBalancer:
#        servers:
#          - url: "https://192.168.1.237:443"
#          - url: "https://192.168.1.238:443"
#          - url: "https://192.168.1.239:443"
#        passHostHeader: true
# Openvpn Loadbalancer
    openvpn:
      loadBalancer:
        servers:
          - url: "https://192.168.1.245:443"
        passHostHeader: true
#endregion
  middlewares:
# Prefix all traffic to admin page
    addprefix-admin:
      addPrefix:
        prefix: "/admin"
# for CrowdSec redirects - File Logging
    crowdsec-bouncer:
      forwardauth:
        address: http://bouncer-traefik:8080/api/v1/forwardAuth
        trustForwardHeader: true
# Redirect all http traffic to https
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
# Add default headers for redirection
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
#
    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
# Whitelist all private IP addresses
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "172.16.0.0/12"
#
    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers

tcp:
  routers:
## Pterodactyl_Wings- Minecraft
    #pterodactyl_wings-minecraft:
    #  entryPoints: wings-minecraft
    #  rule: "HostSNI(`*`)"
    #  service: pterodactyl_wings-minecraft

## OpenVPN
    openvpn:
      rule: "HostSNI(`*`)"
      entryPoints: https
      service: openvpn
      middlewares:
# k3s port
    k3s:
      entryPoints: k3s
      rule: "HostSNI(`*`)"
      service: k3s
      tls: {}
      middlewares:
        - "default-whitelist"
# Load balancers - Services
  services:
## Pterodactyl_Wings-Minecraft
    #pterodactyl_wings-minecraft:
    #  loadBalancer:
    #    servers:
    #      - address: "192.168.1.240:27000"
# k3s loadbalancer
    k3s:
      loadBalancer:
        servers:
        - address: "192.168.1.235:6443"
        - address: "192.168.1.236:6443"
        - address: "192.168.1.237:6443"
## OpenVPN
    openvpn:
      loadBalancer:
        servers:
          - address: "192.168.1.245:443"

# Whitelist all private IP addresses
  middlewares:
    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "172.16.0.0/12"
udp:
  routers:
  # OpenVPN
    openvpn:
      entryPoints: openvpn
      service: openvpn
  services:
  # OpenVPN
    openvpn:
      loadBalancer:
        servers:
          - address: "192.168.1.245:1194"