apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets. These have to be base64
  # echo -n PASSWORD/USERNAME-HERE | base64
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
