version: '3.9'
services:
    rancher:
        command: '--no-cacerts'
        image: 'rancher/rancher:latest'
        privileged: true
        ports:
            - '9443:443'
            - '9080:80'
        networks:
            - proxy
        volumes:
            - ./opt/rancher:/var/lib/rancher
        restart: unless-stopped
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.rancher.entrypoints=http"
          - "traefik.http.routers.rancher.rule=Host(`rancher.cinderblock.tech`)"
          - "traefik.http.middlewares.rancher-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.rancher.middlewares=rancher-https-redirect"
          - "traefik.http.routers.rancher-secure.entrypoints=https"
          - "traefik.http.routers.rancher-secure.rule=Host(`rancher.cinderblock.tech`)"
          - "traefik.http.routers.rancher-secure.tls=true"
          - "traefik.http.routers.rancher-secure.service=rancher"
          - "traefik.http.services.rancher.loadbalancer.server.port=80"
          - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true