version: '3.9'

services:
# Influx Database
  influxdb:
    container_name: influxdb
    image: influxdb:2.7.1-alpine
    restart: unless-stopped
    dns:
      - 192.168.1.253
      - 1.1.1.1
    ports:
      - '8086:8086'
    volumes:
      - './influxdb-data:/var/lib/influxdb2'
      - './etc:/etc/influxdb2'
      # # If you're using self-signed certs, uncomment the lines below
      # - /etc/ssl/cert.pem/:/etc/ssl/cert.pem  
      # - /etc/ssl/cert-key.pem/:/etc/ssl/cert-key.pem
    # command: influxd --tls-cert=/etc/ssl/cert.pem --tls-key=/etc/ssl/cert-key.pem 
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASS}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=1w  #configure data retention by week count
      # The authentication token to associate with the system's initial super-user. If not set, a token will be auto-generated by the system.
    #   - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influx.entrypoints=http"
      - "traefik.http.routers.influx.rule=Host(`influx.cinderblock.tech`)"
      - "traefik.http.middlewares.influx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.influx.middlewares=influx-https-redirect"
      - "traefik.http.routers.influx-secure.entrypoints=https"
      - "traefik.http.routers.influx-secure.rule=Host(`influx.cinderblock.tech`)"
      - "traefik.http.routers.influx-secure.tls=true"
      - "traefik.http.routers.influx-secure.service=influx"
      - "traefik.http.services.influx.loadbalancer.server.port=8086"
      - "traefik.docker.network=proxy"    
    networks:
      - proxy
      - monitoring

networks:
 proxy:
  external: true
 monitoring:
  external: false
  
