---
version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    dns:
      - 192.168.1.253
      - 1.1.1.1
    ports:
      - 9090:9090
    volumes:
      - ./config:/etc/prometheus
      - ./prometheus-data:/prometheus
    command: "--config.file=./config/prometheus.yml"
    restart: unless-stopped
    networks:
      - proxy
      - monitoring
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=http"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.cinderblock.tech`)"
      - "traefik.http.middlewares.prometheus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prometheus.middlewares=prometheus-https-redirect"
      - "traefik.http.routers.prometheus-secure.entrypoints=https"
      - "traefik.http.routers.prometheus-secure.rule=Host(`prometheus.cinderblock.tech`)"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=proxy"    
networks:
  proxy:
    external: true
  monitoring:
    external: false