global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100','192.168.1.240:9100','192.168.1.245:9100','192.168.1.242:9100']

remote_write:
  - url: 'prometheus.cinderblock.tech'
    basic_auth:
      username: ${GRAFANA-USER}
      password: ${GRAFANA-PASS}