---
version: "2"
services:
  homer:
    image: b4bz/homer:latest
    restart: unless-stopped
#To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - ./local/assets/:/www/assets
    ports:
      - 8085:8080
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.entrypoints=http"
      - "traefik.http.routers.homer.rule=Host(`home.local.cinderblook.com`)"
      - "traefik.http.middlewares.homer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homer.middlewares=homer-https-redirect"
      - "traefik.http.routers.homer-secure.entrypoints=https"
      - "traefik.http.routers.homer-secure.rule=Host(`home.local.cinderblook.com`)"
      - "traefik.http.routers.homer-secure.tls=true"
      - "traefik.http.routers.homer-secure.service=homer"
      - "traefik.http.services.homer.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
