#Home assist https://hub.docker.com/r/linuxserver/homeassistant
version: "2.1"
services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/NewYork
    volumes:
      - /path/to/data:/config
    ports:
      - 8123:8123 #optional
    #devices:
      #- /path/to/device:/path/to/device #optional
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassist.entrypoints=http"
      - "traefik.http.routers.homeassist.rule=Host(`homeassist.cinderblock.tech`)"
      - "traefik.http.middlewares.homeassist-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.homeassist.middlewares=homeassist-https-redirect"
      - "traefik.http.routers.homeassist-secure.entrypoints=https"
      - "traefik.http.routers.homeassist-secure.rule=Host(`homeassist.cinderblock.tech`)"
      - "traefik.http.routers.homeassist-secure.tls=true"
      - "traefik.http.routers.homeassist-secure.service=homeassist"
      - "traefik.http.services.homeassist.loadbalancer.server.port=8123"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

