version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
      - ./images:/app/public/images
      - ./icons:/app/public/icons
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dash.entrypoints=http"
      - "traefik.http.routers.dash.rule=Host(`dash.cinderblock.tech`)"
      - "traefik.http.middlewares.dash-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dash.middlewares=dash-https-redirect"
      - "traefik.http.routers.dash-secure.entrypoints=https"
      - "traefik.http.routers.dash-secure.rule=Host(`dash.cinderblock.tech`)"
      - "traefik.http.routers.dash-secure.tls=true"
      - "traefik.http.routers.dash-secure.service=dash"
      - "traefik.http.services.dash.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true