---
- name: Backup volume data from pterodactyl-wing nodes
  hosts: 'pterodactyl-wings'
  gather_facts: true
  become: true

  vars:
    backup_dir: "/backups"
    dest_dir: "{{ backup_dir }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-backup"
    pterodactyl_dirs:
      - "/etc/pterodactyl"
      - "/var/lib/pterodactyl"

  tasks:
    - name: Ensure rsync is installed
      apt:
        name: rsync
        state: present

    - name: Create backup directory
      file:
        path: "{{ dest_dir }}"
        state: directory

    - name: Backup data from pterodactyl directories
      shell: "rsync -az {{ item }} {{ dest_dir }}"
      with_items: "{{ pterodactyl_dirs }}"

    - name: Verify backup
      stat:
        path: "{{ dest_dir }}"
      register: backup_stats

    - name: Print backup status
      debug:
        msg: "Backup successful: {{ backup_stats.stat.exists }}"
