---
- name: Backup volume data from pterodactyl-wing nodes
  hosts: 'pterodactyl-wings'
  gather_facts: true
  become: true

  vars:
    backup_dir: "/home/austin/backups"
    source_dir: "/home/austin/*"
    dest_dir: "{{ backup_dir }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-backup"
    pterodactyl_dirs:
      - "/etc/pterodactyl"
      - "/var/lib/pterodactyl"

  tasks:          
    - name: Create backup directory
      file:
        path: "{{ dest_dir }}"
        state: directory

    - name: Backup data from /etc/pterodactyl
      copy:
        src: "{{ item }}"
        dest: "{{ dest_dir }}/pterodactyl/etc/{{ item | basename }}"
      loop: "{{ pterodactyl_dirs }}"

    - name: Backup data from /var/lib/pterodactyl
      copy:
        src: "{{ item }}"
        dest: "{{ dest_dir }}"
      with_fileglob: "{{ source_dir }}"

    - name: Backup data from /var/lib/pterodactyl
      copy:
        src: "{{ item }}"
        dest: "{{ dest_dir }}/pterodactyl/var/{{ item | basename }}"
      loop: "{{ pterodactyl_dirs }}"

    - name: Verify backup
      stat:
        path: "{{ dest_dir }}"
      register: backup_stats

    - name: Print backup status
      debug:
        msg: "Backup successful: {{ backup_stats.stat.exists }}"
