# Start a Docker Container with Node-expose running for data monitoring on Grafana
- name: Start Node Exporter on all hosts
  hosts: '*'
  become: yes
  vars:
      path_src: "~/cadvisor/"


  tasks:
    - name: Create directory for cadvisor
      file:
        path: "{{ path_src }}"
        state: directory
        mode: '0755'  

    - name: Start cadvisor container
      docker_compose:
        project_name: cadvisor
        definition:
          version: '3.9'
          services:
            cadvisor:
              image: gcr.io/cadvisor/cadvisor
              container_name: monitoring_cadvisor
              restart: unless-stopped
              privileged: true
              volumes:
                - /:/rootfs:ro
                - /var/run:/var/run:rw
                - /sys:/sys:ro
                - /var/lib/docker/:/var/lib/docker:ro
              command:
                - '--path.procfs=/host/proc'
                - '--path.rootfs=/rootfs'
                - '--path.sysfs=/host/sys'
                - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
              ports:
                - 9110:8080
        state: present







