- name: install latest qemu-guest-agent
  hosts: "*"
  become: true
  become_method: sudo
  tasks:
    - name: install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true