# Installs K3S cluster using three nodes. Considers first node to be primary/master.
# Pulls k3s_token 
---
- name: Deploy K3s Cluster
  hosts: k3s_nodes
  become: yes

  vars:
    primary_master: "{{ groups['k3s_nodes'][0] }}" 

  tasks:
    - name: Install required packages
      apt:
        name: ['curl']
        state: present

    - name: Download and install k3s on primary master
      command: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.4+k3s1 INSTALL_K3S_EXEC="--cluster-init" sh -
      when: inventory_hostname == primary_master

    - name: Retrieve K3s token on primary master
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token
      when: inventory_hostname == primary_master

    - name: Save K3s token on primary master to a file
      copy:
        content: "{{ k3s_token.stdout }}"
        dest: k3s_token.txt
      when: inventory_hostname == primary_master

    - name: Join other nodes as workers
      command: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.4+k3s1 K3S_URL=https://{{ hostvars[primary_master].inventory_hostname }}:6443 K3S_TOKEN=$(cat /var/lib/rancher/k3s/server/node-token) sh -
      when: inventory_hostname != primary_master
