# Installs K3S cluster using three nodes. Considers first node to be primary/master.
# Pulls k3s_token 
---
- name: Deploy K3s Cluster
  hosts: k3s_nodes
  become: yes

  vars:
    primary_master: "{{ groups['k3s_nodes'][0] }}" 

  tasks:
    - name: Install required packages
      apt:
        name: ['curl']
        state: present

    - name: Download and install k3s on primary master
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.4+k3s1 INSTALL_K3S_EXEC="--cluster-init" sh -
      when: inventory_hostname == primary_master

    - name: Retrieve K3s token on primary master
      shell: cat /var/lib/rancher/k3s/server/node-token
      register: k3s_token_output
      when: inventory_hostname == primary_master

    - name: Save K3s token on primary master to a variable
      set_fact:
        k3s_token: "{{ k3s_token_output.stdout }}"
      when: inventory_hostname == primary_master
    
    - name: Share K3s token with all hosts
      set_fact:
        k3s_token: "{{ hostvars[primary_master].k3s_token }}"
      run_once: true

    - name: Join other nodes as workers
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v1.21.4+k3s1 K3S_URL=https://{{ hostvars[primary_master].inventory_hostname }}:6443 K3S_TOKEN={{ k3s_token }} sh
      when: inventory_hostname != primary_master
