---
- hosts: "*"
  gather_facts: no
  tasks:
    - name: Restart ssh daemon
      service:
        name: ssh
        state: restarted
      become: true
      ignore_errors: yes
    - name: Restart sssd daemon
      service:
        name: sssd
        state: stopped
      ignore_errors: yes
      become: true
    - name: Restart httpd daemon
      service:
        name: httpd
        state: started
      become: true