---
- name: change DNS server
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses: 
      - "{{ groups['pdc'][0] }}"
      - "{{ groups['rdc'][0] }}"

- name: join domain
  win_domain_membership:
    dns_domain_name: "{{ domain }}"
    hostname: "{{ primary_fileshare_server }}"
    domain_admin_user: "{{ domain_admin }}"
    domain_admin_password: "{{ domain_admin_password }}"
    state: domain
  register: domain_joined

- name: reboot after domain join
  win_reboot:
  when: domain_joined.reboot_required

# Create file structures for shares
  # Top level share
- name: Create directory
  ansible.windows.win_file:
    path: C:\Share
    state: directory
  # Share for Employee
- name: Create directory
  ansible.windows.win_file:
    path: C:\Share\Employee
    state: directory
  # Share for Admin
- name: Create directory
  ansible.windows.win_file:
    path: C:\Share\Admin
    state: directory
  # Create Files to put in shares
- name: Create Employee Files
  ansible.windows.win_file:
    path: C:\Share\Employee\Employeedata.txt
    state: touch
- name: Create Admin Files
  ansible.windows.win_file:
    path: C:\Share\Admin\Admindata.txt
    state: touch
# Assign share permissions
- name: Add public employee share
  ansible.windows.win_share:
    name: EmployeeShare
    description: Sharing is Caring
    path: C:\Share\Employee\
    list: yes
    full: Domain Admins
    read: Everyone
- name: Add admin only share
  ansible.windows.win_share:
    name: AdminShare
    description: Super Secret, professionals only
    path: C:\Share\Admin\
    list: yes
    full: Domain Admins
    read: Domain Admins
    deny: Everyone