---
- name: Backup home directory data from VMs
  hosts: '*'
  gather_facts: true
  become: false

  vars:
    backup_dir: "/backups"
    source_dir: "/home/austin"
    dest_dir: "{{ backup_dir }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-backup"

  tasks:
    - name: Create backup directory
      file:
        path: "{{ dest_dir }}"
        state: directory
      delegate_to: localhost

    - name: Create archive of the source directory
      become: true
      shell: "tar -czf /tmp/{{ inventory_hostname }}.tar.gz -C {{ source_dir }} ."

    - name: Fetch the archive file
      become: false
      fetch:
        src: "/tmp/{{ inventory_hostname }}.tar.gz"
        dest: "{{ dest_dir }}"
        flat: yes

    - name: Verify backup
      stat:
        path: "{{ dest_dir }}"
      register: backup_stats
      delegate_to: localhost

    - name: Print backup status
      debug:
        msg: "Backup successful: {{ backup_stats.stat.exists }}"
      delegate_to: localhost
