---
- name: Backup volume data from pterodactyl-wing nodes
  hosts: 'pterodactyl-wings'
  gather_facts: true
  become: true

  vars:
    backup_dir: "/backups"
    dest_dir: "{{ backup_dir }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-backup"
    pterodactyl_dirs:
      - "/etc/pterodactyl"
      - "/var/lib/pterodactyl"

  tasks:
    - name: Create backup directory
      file:
        path: "{{ dest_dir }}"
        state: directory
      delegate_to: localhost

    - name: Backup data from pterodactyl node
      fetch:
        src: "{{ item }}"
        dest: "{{ dest_dir }}/{{ item | basename }}"
        flat: yes
      loop: "{{ pterodactyl_dirs }}"

    - name: Verify backup
      stat:
        path: "{{ dest_dir }}"
      register: backup_stats
      delegate_to: localhost

    - name: Print backup status
      debug:
        msg: "Backup successful: {{ backup_stats.stat.exists }}"
      delegate_to: localhost
