---
- name: Backup home directory data from VMs
  hosts: '*'
  gather_facts: true
  become: true

  vars:
    backup_dir: "/backups"
    source_dir: "/home/austin"
    dest_dir: "{{ backup_dir }}/{{ inventory_hostname }}-{{ ansible_date_time.date }}-backup"

  tasks:
    - name: Create backup directory
      file:
        path: "{{ dest_dir }}"
        state: directory
      delegate_to: localhost

    - name: Get list of files in source_dir
      find:
        paths: "{{ source_dir }}"
        recurse: yes
        excludes: "backups"
      register: files_to_copy

    - name: Backup data
      fetch:
        src: "{{ item.path }}"
        dest: "{{ dest_dir }}"
        flat: yes
      loop: "{{ files_to_copy.files }}"

    - name: Verify backup
      stat:
        path: "{{ dest_dir }}"
      register: backup_stats
      delegate_to: localhost

    - name: Print backup status
      debug:
        msg: "Backup successful: {{ backup_stats.stat.exists }}"
      delegate_to: localhost
