[AnsibleSwitches] 
10.175.135.85
10.175.135.86 
10.175.135.87 
10.175.135.88
[AnsibleSwitches:vars] 
ansible_user=username
ansible_password=passwordd
ansible_connection=cli 
ansible_network_os=ios

[AnsibleSwitch1] 
10.175.135.85
[AnsibleSwitch1:vars] 
ansible_user=username
ansible_password=passwordd
ansible_connection=cli 
ansible_network_os=ios

[AnsibleSwitch2] 
10.175.135.86
[AnsibleSwitch2:vars] 
ansible_user=username
ansible_password=passwordd
ansible_connection=cli 
ansible_network_os=ios


[AnsibleSwitch3] 
10.175.135.87
[AnsibleSwitch3:vars] 
ansible_user=username
ansible_password=passwordd
ansible_connection=cli 
ansible_network_os=ios

[AnsibleSwitch4] 
10.175.135.88 
[AnsibleSwitch4:vars] 
ansible_user=username
ansible_password=passwordd
ansible_connection=cli 
ansible_network_os=ios
